version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/xmas-web
hooks:
  ApplicationStart:
  - location: bin/app-start
    timeout: 60
    runas: ubuntu
  ApplicationStop:
  - location: bin/app-stop
    timeout: 60
    runas: ubuntu