version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/xmas-web
hooks:
ApplicationStart:
  - location: bin/appstart
    timeout: 60
    runas: ubuntu
ApplicationStop:
  - location: bin/appstop
    timeout: 60
    runas: ubuntu